[workspace]
resolver = "2"
members = [
  "D*/",
  "d*/"
]

[workspace.package]
name = "advent-of-code-2023"
version = "0.0.0"
edition = "2021"
license = "AGPL-3.0"
publish = false

[workspace.dependencies]
divan = "0.1"

